[package]
name = "kebpf"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
ax-feat.workspace = true
ax-log.workspace = true
ax-errno.workspace = true
ax-hal.workspace = true
ax-io.workspace = true
starry-kernel.workspace = true

kmod-tools = "0.2"
kbpf-basic = "0.5"

[features]
default = []
qemu = [
    "ax-feat/defplat",
    "ax-feat/display",
    "starry-kernel/input",
    "starry-kernel/vsock",
    "ax-feat/fs-ng-times",
    "starry-kernel/dev-log",
]
smp = ["ax-feat/smp"]

vf2 = ["ax-hal/riscv64-visionfive2"]
