/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/socket.h>

int main(void)
{
	errno = 0;
	int r = accept(-1, NULL, NULL);
	int e = errno;
	dprintf(1, "CASE accept.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

