/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>


static const char p[] = "/__starryos_probe_access__/not_there";
int main(void)
{
	errno = 0;
	int r = access(p, F_OK);
	int e = errno;
	dprintf(1, "CASE access.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

