/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <linux/capability.h>
#include <stdio.h>
#include <sys/syscall.h>
int main(void)
{
	struct __user_cap_header_struct h = {_LINUX_CAPABILITY_VERSION_3, 0};
	struct __user_cap_data_struct d[2];
	errno = 0;
	long r = syscall(SYS_capget, &h, d);
	int e = errno;
	dprintf(1, "CASE capget_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
