/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>


static const char p[] = "/__starryos_probe_chmod__/not_there";
int main(void)
{
	errno = 0;
	int r = chmod(p, 0777);
	int e = errno;
	dprintf(1, "CASE chmod.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

