/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <time.h>

int main(void)
{
	errno = 0;
	int r = clock_getres(CLOCK_REALTIME, NULL);
	int e = errno;
	dprintf(1, "CASE clock_getres.null_ptr ret=%d errno=%d note=handwritten\n", r, e);
	return 0;
}

