/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <time.h>
int main(void)
{
	struct timespec rq = {0, 0}, rm;
	errno = 0;
	long r = clock_nanosleep(CLOCK_REALTIME, 0, &rq, &rm);
	int e = errno;
	dprintf(1, "CASE clock_nanosleep_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
