/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

#ifndef AT_FDCWD
#define AT_FDCWD (-100)
#endif

static const char p[] = "/__starryos_probe_faccessat__/not_there";
int main(void)
{
	errno = 0;
	int r = faccessat(AT_FDCWD, p, F_OK, 0);
	int e = errno;
	dprintf(1, "CASE faccessat.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

