/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

int main(void)
{
	errno = 0;
	int r = fchmod(-1, 0777);
	int e = errno;
	dprintf(1, "CASE fchmod.badfd ret=%d errno=%d note=handwritten\n", r, e);
	return 0;
}

