/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <unistd.h>

#ifndef AT_FDCWD
#define AT_FDCWD (-100)
#endif

static const char p[] = "/__starryos_probe_fchmodat2__/not_there";
int main(void)
{
	errno = 0;
	int r = (int)syscall(SYS_fchmodat, AT_FDCWD, p, 0777, 0);
	int e = errno;
	dprintf(1, "CASE fchmodat2.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

