/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	int r = fchown(-1, (uid_t)-1, (gid_t)-1);
	int e = errno;
	dprintf(1, "CASE fchown.badfd ret=%d errno=%d note=handwritten\n", r, e);
	return 0;
}

