/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/statfs.h>

int main(void)
{
	errno = 0;
	struct statfs sf; int r = fstatfs(-1, &sf);
	int e = errno;
	dprintf(1, "CASE fstatfs.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

