/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/stat.h>

int main(void)
{
	errno = 0;
	struct stat st; int r = fstat(-1, &st);
	int e = errno;
	dprintf(1, "CASE fstat.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

