/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>
int main(void)
{
	void *head_ptr = NULL;
	size_t len = 0;
	errno = 0;
	long r = syscall(SYS_get_robust_list, 0, &head_ptr, &len);
	int e = errno;
	dprintf(1, "CASE get_robust_list_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
