/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/time.h>

int main(void)
{
	errno = 0;
	int r = getitimer(ITIMER_REAL, NULL);
	int e = errno;
	dprintf(1, "CASE getitimer.null_val ret=%d errno=%d note=handwritten\n", r, e);
	return 0;
}

