/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/resource.h>
int main(void)
{
	errno = 0;
	long r = (long)getpriority(PRIO_PROCESS, 0);
	int e = errno;
	dprintf(1, "CASE getpriority_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
