/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/random.h>
int main(void)
{
	char b[16];
	errno = 0;
	long r = getrandom(b, sizeof(b), 0);
	int e = errno;
	dprintf(1, "CASE getrandom_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
