/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/resource.h>
int main(void)
{
	struct rusage ru;
	errno = 0;
	long r = getrusage(RUSAGE_SELF, &ru);
	int e = errno;
	dprintf(1, "CASE getrusage_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
