/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/socket.h>

int main(void)
{
	errno = 0;
	int v; socklen_t l = sizeof(v); int r = getsockopt(-1, SOL_SOCKET, SO_TYPE, &v, &l);
	int e = errno;
	dprintf(1, "CASE getsockopt.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

