/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>


static const char p[] = "/__starryos_probe_lchown__/not_there";
int main(void)
{
	errno = 0;
	int r = lchown(p, (uid_t)-1, (gid_t)-1);
	int e = errno;
	dprintf(1, "CASE lchown.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

