/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/mount.h>


static const char p[] = "/__starryos_probe_mount__/not_there";
int main(void)
{
	errno = 0;
	int r = mount(p, "/__starryos_probe_mount__/tgt", "ext4", 0, NULL);
	int e = errno;
	dprintf(1, "CASE mount.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

