/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <time.h>
int main(void)
{
	struct timespec ts = {0, 0};
	errno = 0;
	long r = nanosleep(&ts, NULL);
	int e = errno;
	dprintf(1, "CASE nanosleep_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
