/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/stat.h>

#ifndef AT_FDCWD
#define AT_FDCWD (-100)
#endif

static const char p[] = "/__starryos_probe_newfstatat__/not_there";
int main(void)
{
	errno = 0;
	struct stat st; int r = fstatat(AT_FDCWD, p, &st, 0);
	int e = errno;
	dprintf(1, "CASE newfstatat.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

