/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <sys/syscall.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	int r = (int)syscall(SYS_pidfd_send_signal, -1, SIGKILL, NULL, 0);
	int e = errno;
	dprintf(1, "CASE pidfd_send_signal.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

