/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	int r = (int)syscall(SYS_pidfd_getfd, -1, -1, 0);
	int e = errno;
	dprintf(1, "CASE pidfd_getfd.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

