/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/prctl.h>
int main(void)
{
	errno = 0;
	long r = prctl(-1, 0, 0, 0, 0);
	int e = errno;
	dprintf(1, "CASE prctl_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
