/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/resource.h>
int main(void)
{
	struct rlimit rl;
	errno = 0;
	long r = prlimit64(0, RLIMIT_NOFILE, NULL, &rl);
	int e = errno;
	dprintf(1, "CASE prlimit64_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
