/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

#ifndef AT_FDCWD
#define AT_FDCWD (-100)
#endif

static const char p[] = "/__starryos_probe_readlinkat__/not_there";
int main(void)
{
	errno = 0;
	char b[256];
	ssize_t r = readlinkat(AT_FDCWD, p, b, sizeof(b));
	int e = errno;
	dprintf(1, "CASE readlinkat.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

