/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>

static const char p[] = "/__starryos_probe_readlink__/not_there";
int main(void)
{
	errno = 0;
	char b[256];
	ssize_t r = readlink(p, b, sizeof(b));
	int e = errno;
	dprintf(1, "CASE readlink.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

