/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#ifndef SIGUSR1
#define SIGUSR1 10
#endif
int main(void)
{
	struct sigaction old;
	errno = 0;
	long r = sigaction(SIGUSR1, NULL, &old);
	int e = errno;
	dprintf(1, "CASE rt_sigaction_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
