/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/syscall.h>
#ifndef SIGUSR1
#define SIGUSR1 10
#endif
int main(void)
{
	siginfo_t info;
	memset(&info, 0, sizeof(info));
	errno = 0;
	long r = syscall(SYS_rt_sigqueueinfo, -1, SIGUSR1, &info);
	int e = errno;
	dprintf(1, "CASE rt_sigqueueinfo_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
