/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
int main(void)
{
	sigset_t empty;
	sigemptyset(&empty);
	errno = 0;
	long r = sigprocmask(SIG_BLOCK, &empty, NULL);
	int e = errno;
	dprintf(1, "CASE rt_sigprocmask_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
