/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
int main(void)
{
	sigset_t set;
	errno = 0;
	long r = sigpending(&set);
	int e = errno;
	dprintf(1, "CASE rt_sigpending_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
