/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sched.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	unsigned long m; int r = sched_getaffinity(0, sizeof(m), NULL);
	int e = errno;
	dprintf(1, "CASE sched_getaffinity.null_mask ret=%d errno=%d note=handwritten\n", r, e);
	return 0;
}

