/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <sched.h>
#include <stdio.h>
int main(void)
{
	struct sched_param sp = {0};
	errno = 0;
	long r = sched_setscheduler(0, -1, &sp);
	int e = errno;
	dprintf(1, "CASE sched_setscheduler_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
