/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <sched.h>
#include <stdio.h>
int main(void)
{
	errno = 0;
	long r = (long)sched_yield();
	int e = errno;
	dprintf(1, "CASE sched_yield_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
