/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>

int main(void)
{
	errno = 0;
	struct msghdr mh;
	memset(&mh, 0, sizeof(mh));
	ssize_t r = sendmsg(-1, &mh, 0);
	int e = errno;
	dprintf(1, "CASE sendmsg.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

