/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/socket.h>

int main(void)
{
	errno = 0;
	char b = 0; ssize_t r = sendto(-1, &b, 1, 0, NULL, 0);
	int e = errno;
	dprintf(1, "CASE sendto.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

