/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>
int main(void)
{
	errno = 0;
	long r = (long)syscall(SYS_set_tid_address, NULL);
	int e = errno;
	long out = (r != -1L && e == 0) ? 0L : r;
	dprintf(1, "CASE set_tid_address_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", out, e);
	return 0;
}
