/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/syscall.h>
int main(void)
{
	errno = 0;
	long r = syscall(SYS_set_robust_list, (void *)0, 0);
	int e = errno;
	dprintf(1, "CASE set_robust_list_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
