/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
int main(void)
{
	gid_t g = 0;
	errno = 0;
	long r = (long)setgroups(-1, &g);
	int e = errno;
	dprintf(1, "CASE setgroups_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
