/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
int main(void)
{
	errno = 0;
	long r = (long)setresgid((gid_t)-1, (gid_t)-1, (gid_t)-1);
	int e = errno;
	dprintf(1, "CASE setresgid_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
