/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
int main(void)
{
	errno = 0;
	pid_t p = setsid();
	int e = errno;
	long r = (p > 0 && e == 0) ? 0L : (long)p;
	dprintf(1, "CASE setsid_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
