/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/socket.h>

int main(void)
{
	errno = 0;
	int v = 1; int r = setsockopt(-1, SOL_SOCKET, SO_REUSEADDR, &v, sizeof(v));
	int e = errno;
	dprintf(1, "CASE setsockopt.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

