/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/socket.h>

int main(void)
{
	errno = 0;
	int r = shutdown(-1, SHUT_RDWR);
	int e = errno;
	dprintf(1, "CASE shutdown.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

