/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
int main(void)
{
	stack_t ss, oss;
	memset(&ss, 0, sizeof(ss));
	ss.ss_flags = SS_DISABLE;
	errno = 0;
	long r = sigaltstack(&ss, &oss);
	int e = errno;
	dprintf(1, "CASE sigaltstack_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
