/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <linux/stat.h>
#include <sys/syscall.h>
#include <unistd.h>


#ifndef AT_FDCWD
#define AT_FDCWD (-100)
#endif

static const char p[] = "/__starryos_probe_statx__/not_there";
int main(void)
{
	errno = 0;
	struct statx stx; long r = syscall(SYS_statx, AT_FDCWD, p, 0, STATX_BASIC_STATS, &stx);
	int e = errno;
	dprintf(1, "CASE statx.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

