/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/stat.h>


static const char p[] = "/__starryos_probe_stat__/not_there";
int main(void)
{
	errno = 0;
	struct stat st; int r = stat(p, &st);
	int e = errno;
	dprintf(1, "CASE stat.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

