/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/statfs.h>


static const char p[] = "/__starryos_probe_statfs__/not_there";
int main(void)
{
	errno = 0;
	struct statfs sf; int r = statfs(p, &sf);
	int e = errno;
	dprintf(1, "CASE statfs_linux_contract.p1 ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

