/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/sysinfo.h>
int main(void)
{
	struct sysinfo si;
	errno = 0;
	long r = sysinfo(&si);
	int e = errno;
	dprintf(1, "CASE sysinfo_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
