/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/mount.h>


static const char p[] = "/__starryos_probe_umount2__/not_there";
int main(void)
{
	errno = 0;
	int r = umount2(p, 0);
	int e = errno;
	dprintf(1, "CASE umount2.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

