/* Generated by materialize (tbd_p1) */
#include <errno.h>
#include <stdio.h>
#include <sys/utsname.h>
int main(void)
{
	struct utsname u;
	errno = 0;
	long r = uname(&u);
	int e = errno;
	dprintf(1, "CASE uname_linux_contract.p1 ret=%ld errno=%d note=tbd_p1\n", r, e);
	return 0;
}
