/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <utime.h>


static const char p[] = "/__starryos_probe_utime__/not_there";
int main(void)
{
	errno = 0;
	int r = utime(p, NULL);
	int e = errno;
	dprintf(1, "CASE utime.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

