/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/time.h>


static const char p[] = "/__starryos_probe_utimes__/not_there";
int main(void)
{
	errno = 0;
	int r = utimes(p, NULL);
	int e = errno;
	dprintf(1, "CASE utimes.enoent ret=%d errno=%d note=handwritten\n", (int)r, e);
	return 0;
}

